# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{
  services.zapret ={
    enable = true;
    params = ["--filter-tcp=443 --hostlist-domains=youtube.com,googlevideo.com,ggpht.com,yting.com,youtubei.googleapis.com --dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=1 --new"
"--filter-tcp=443 --hostlist-domains=phncdn.com,xvideos-cdn.com --dpi-desync=fake --dpi-desync-fooling=badseq --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt --new"
"--filter-udp=443 --hostlist-domains=googlevideo.com --dpi-desync=fake --dpi-desync-repeats=6 --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt --new"
"--filter-udp=7443 --hostlist-domains=ggpht.com --dpi-desync=fake,udplen --dpi-desync-udplen-increment=4 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin --dpi-desync-cutoff=n3 --dpi-desync-repeats=2 --dpi-desync-autottl --new"
"--filter-tcp=7443 --hostlist-domains=ggpht.com --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=1 --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-fake-tls-mod=rnd,padencap --dpi-desync-split-seqovl-pattern=/opt/zapret/files/fake/tls_clienthello_iana_org.bin --dpi-desync-autottl --new"
"--filter-tcp=80 --dpi-desync=fake,multisplit --dpi-desync-split-pos=sld+1 --dpi-desync-fooling=md5sig --dpi-desync-autottl --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt --new"
"--filter-udp=7443 --dpi-desync=fake,udplen --dpi-desync-udplen-increment=4 --dpi-desync-fake-quic=/opt/zapret/files/fake/quic_initial_vk_com.bin --dpi-desync-cutoff=n3 --dpi-desync-repeats=2 --dpi-desync-autottl --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt --new"
"--filter-tcp=7443 --hostlist-domains=googlevideo.com --dpi-desync=fake,multisplit --dpi-desync-split-pos=1,midsld --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-autottl --new"
"--filter-tcp=7443 --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=1 --dpi-desync-fooling=md5sig,badseq --dpi-desync-fake-tls=/opt/zapret/files/fake/tls_clienthello_www_google_com.bin --dpi-desync-fake-tls-mod=rnd,padencap --dpi-desync-split-seqovl-pattern=/opt/zapret/files/fake/tls_clienthello_iana_org.bin --dpi-desync-autottl --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt --new"
"--filter-udp=50000-50090 --filter-l7=discord,stun --dpi-desync=fake --hostlist=/opt/zapret/ipset/zapret-hosts-user.txt --hostlist=/opt/zapret/ipset/zapret-hosts.txt.gz --hostlist-exclude=/opt/zapret/ipset/zapret-hosts-user-exclude.txt"
    ];
    #whitelist = ["youtube.com" "googlevideo.com" "ytimg.com" "youtu.be" "discord.com"]; #--dpi-desync-fwmark=0x40000000
    udpSupport = true;
    udpPorts = ["443" "7443" "50000-50099"];
  };
}
