# ── Desktop: AMD CPU + NVIDIA GPU ─────────────────────────────────────────────
# Everything below is a switch defined in modules/nixos/**. Hardware facts live in
# hardware-configuration.nix (generated by nixos-generate-config — copy yours in).
{ pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ];

  my = {
    # ── Identity ─────────────────────────────────────────── CHANGEME ──
    user = {
      name = "user"; # also rename users/user/ to match
      fullName = "Your Name";
      email = "you@example.com";
      shell = "zsh"; # "zsh" | "fish" | "bash"
      # extraGroups = [ "dialout" ];
      # initialPassword is only used when the account is created; existing users keep theirs.
    };
    locale = {
      timeZone = "Europe/Berlin";
      defaultLocale = "en_US.UTF-8";
      keyboard.layout = "us";
    };
    nix.flakePath = "/etc/nixos"; # where this repo lives → `nh os switch` needs no arguments

    # ── Hardware ──────────────────────────────────────────────────────
    hardware = {
      cpu = "amd";
      gpu = "nvidia";
      nvidia = {
        open = true; # RTX 20xx / GTX 16xx and newer. GTX 10xx or older → false
        driver = "cachyos"; # pre-built for the CachyOS kernel. Alternatives: "latest" "beta" "stable"
      };
    };

    # ── Boot ──────────────────────────────────────────────────────────
    boot = {
      kernel = "cachyos"; # "cachyos-znver4" for Zen 4/5, "cachyos-gcc" if a module misbehaves
      scx.scheduler = "scx_lavd"; # latency-first: best for gaming
      limine.secureBoot = false; # see modules/nixos/core/boot.nix before enabling
    };

    # ── Storage ── the btrfs mount points from hardware-configuration.nix
    filesystem.btrfs.mountpoints = [
      "/"
      "/home"
      "/nix"
    ];

    # ── Desktop & workloads ───────────────────────────────────────────
    desktop.plasma.enable = true;

    gaming = {
      enable = true;
      xone.enable = false; # Xbox wireless dongle (out-of-tree module)
      xpadneo.enable = false; # Xbox controllers over Bluetooth (out-of-tree module)
    };

    development = {
      enable = true;
      languages = [
        "c"
        "rust"
        "python"
        "node"
      ];
      editors = [ "vscode" ];
    };

    virtualisation = {
      docker.enable = true;
      libvirt.enable = true;
      distrobox.enable = true;
    };

    services = {
      printing.enable = true;
      flatpak.enable = true;
      ssh.enable = false;
      tailscale.enable = false;
    };
  };

  # Host-only extras that don't deserve their own module
  environment.systemPackages = with pkgs; [
    # openrgb
  ];
  # services.hardware.openrgb.enable = true;

  # CHANGEME: copy the value from your current /etc/nixos/configuration.nix.
  # It records the release you first installed; never bump it blindly.
  system.stateVersion = "25.11";
}
